### ISSUE TITLE
Check requirements

### ISSUE THREAD

**Issue by ananafrida** [n-aggarwal/comp-333-2#18]

**Comment by ananafrida** [comment]
@n-aggarwal  is this case handled? "If a user is already logged in and requests the registration page, they should be redirected to the index page with the overview of all rated songs"

**Comment by n-aggarwal** [comment]
It should be! I know for a fact that was the case when I merged the registration page pr. I can test it once again tonight.

**Comment by ananafrida** [comment]
I cleared my cache and it worked for me too. All good.
